import { createCn } from "cn/config"

export const textTokens = [
  "hero",
  "hero-compact",
  "lede",
  "lede-compact",
  "stat",
  "unit",
  "section",
  "topic",
  "topic-compact",
  "question",
  "question-compact",
  "answer",
  "answer-compact",
  "score",
  "results",
  "figure",
  "row",
  "meta",
  "caption",
  "eyebrow",
  "eyebrow-compact",
  "brand",
  "brand-compact",
  "nav",
  "nav-compact",
  "button",
  "button-lg",
  "button-sm",
  "pill",
  "pill-compact",
  "pill-lg",
  "pill-xs",
  "chip",
  "glyph",
  "logo",
  "logo-compact",
  "avatar",
  "toggle",
]

export const radiusTokens = [
  "pill",
  "chip",
  "code",
  "tile-sm",
  "tile-md",
  "tile",
  "control-sm",
  "icon",
  "control",
  "control-lg",
  "answer-compact",
  "answer",
  "row",
  "card",
  "hero",
  "artboard",
  "phone",
]

export const shadowTokens = [
  "card",
  "stat",
  "artboard",
  "card-hover",
  "focus-card",
  "focus-card-hover",
  "logo",
  "cta",
  "cta-next",
  "cta-compact",
  "selected",
  "score-ring",
  "score-hero",
  "progress-glow",
  "progress-glow-compact",
  "dot",
]

export const cn = createCn({
  extend: {
    theme: {
      text: textTokens,
      radius: radiusTokens,
      shadow: shadowTokens,
      blur: ["glass", "header"],
      tracking: ["badge", "streak", "label"],
      spacing: ["gutter", "gutter-compact"],
    },
  },
})
